Url_Ticker_Spot = "https://api.binance.com/api/v1/ticker/24hr"
URL_Ticker_UFuture = "https://fapi.binance.com/fapi/v1/ticker/24hr"
URL_Ticker_CFuture = "https://dapi.binance.com/dapi/v1/ticker/24hr"
URL_Base_Download = "https://data.binance.vision"
URL_Base_S3 = "https://s3-ap-northeast-1.amazonaws.com/data.binance.vision"
